spring.application.name=gestion-rh-backend
server.port=${SPRING_PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/gestion_rh?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:admin}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:admin123}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

management.endpoint.health.probes.enabled=true
management.endpoints.web.exposure.include=health,info

# Error handling
server.error.include-message=always
server.error.include-stacktrace=never
server.error.include-exception=false

# Logging
logging.level.root=INFO
logging.level.com.gestionrh=DEBUG
logging.level.org.springframework.mail=DEBUG

# Mail SMTP configurable par variable d'environnement
# Par défaut, l'application utilise Ethereal Email pour le dev.
# Pour Gmail, fournissez un mot de passe d'application valides.

spring.mail.host=${SPRING_MAIL_HOST:smtp.ethereal.email}
spring.mail.port=${SPRING_MAIL_PORT:587}
spring.mail.username=${SPRING_MAIL_USERNAME:stevie.hintz11@ethereal.email}
spring.mail.password=${SPRING_MAIL_PASSWORD:MbSp2D6e9z7KSpvyY4}
spring.mail.properties.mail.smtp.auth=${SPRING_MAIL_SMTP_AUTH:true}
spring.mail.properties.mail.smtp.starttls.enable=${SPRING_MAIL_STARTTLS_ENABLE:true}
spring.mail.properties.mail.smtp.starttls.required=${SPRING_MAIL_STARTTLS_REQUIRED:true}
spring.mail.default-encoding=UTF-8
spring.mail.properties.mail.transport.protocol=smtp
spring.mail.properties.mail.debug=false
